// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFf4859d9DecodeKonamiBackendInternalPkgModels(in *jlexer.Lexer, out *UserSubscription) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "targetId":
			out.TargetId = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFf4859d9EncodeKonamiBackendInternalPkgModels(out *jwriter.Writer, in UserSubscription) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"targetId\":"
		out.RawString(prefix[1:])
		out.Int(int(in.TargetId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserSubscription) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFf4859d9EncodeKonamiBackendInternalPkgModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserSubscription) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFf4859d9EncodeKonamiBackendInternalPkgModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserSubscription) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFf4859d9DecodeKonamiBackendInternalPkgModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserSubscription) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFf4859d9DecodeKonamiBackendInternalPkgModels(l, v)
}
