// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package usecase

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson397c489bDecodeKonamiBackendInternalPkgCsrfUsecase(in *jlexer.Lexer, out *TokenMeta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SessionID":
			out.SessionID = string(in.String())
		case "TimeStamp":
			out.TimeStamp = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson397c489bEncodeKonamiBackendInternalPkgCsrfUsecase(out *jwriter.Writer, in TokenMeta) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SessionID\":"
		out.RawString(prefix[1:])
		out.String(string(in.SessionID))
	}
	{
		const prefix string = ",\"TimeStamp\":"
		out.RawString(prefix)
		out.Int64(int64(in.TimeStamp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TokenMeta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson397c489bEncodeKonamiBackendInternalPkgCsrfUsecase(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TokenMeta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson397c489bEncodeKonamiBackendInternalPkgCsrfUsecase(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TokenMeta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson397c489bDecodeKonamiBackendInternalPkgCsrfUsecase(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TokenMeta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson397c489bDecodeKonamiBackendInternalPkgCsrfUsecase(l, v)
}
