// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package meeting is a generated GoMock package.
package meeting

import (
	gomock "github.com/golang/mock/gomock"
	models "konami_backend/internal/pkg/models"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateMeeting mocks base method
func (m *MockRepository) CreateMeeting(meeting models.Meeting) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeeting", meeting)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeeting indicates an expected call of CreateMeeting
func (mr *MockRepositoryMockRecorder) CreateMeeting(meeting interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeeting", reflect.TypeOf((*MockRepository)(nil).CreateMeeting), meeting)
}

// GetMeeting mocks base method
func (m *MockRepository) GetMeeting(meetingId, userId int, authorized bool) (models.MeetingDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeeting", meetingId, userId, authorized)
	ret0, _ := ret[0].(models.MeetingDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeeting indicates an expected call of GetMeeting
func (mr *MockRepositoryMockRecorder) GetMeeting(meetingId, userId, authorized interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeeting", reflect.TypeOf((*MockRepository)(nil).GetMeeting), meetingId, userId, authorized)
}

// UpdateMeeting mocks base method
func (m *MockRepository) UpdateMeeting(userId int, update models.MeetingUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeeting", userId, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMeeting indicates an expected call of UpdateMeeting
func (mr *MockRepositoryMockRecorder) UpdateMeeting(userId, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeeting", reflect.TypeOf((*MockRepository)(nil).UpdateMeeting), userId, update)
}

// GetNextMeetings mocks base method
func (m *MockRepository) GetNextMeetings(params FilterParams) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextMeetings", params)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextMeetings indicates an expected call of GetNextMeetings
func (mr *MockRepositoryMockRecorder) GetNextMeetings(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextMeetings", reflect.TypeOf((*MockRepository)(nil).GetNextMeetings), params)
}

// GetTopMeetings mocks base method
func (m *MockRepository) GetTopMeetings(params FilterParams) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopMeetings", params)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopMeetings indicates an expected call of GetTopMeetings
func (mr *MockRepositoryMockRecorder) GetTopMeetings(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopMeetings", reflect.TypeOf((*MockRepository)(nil).GetTopMeetings), params)
}

// FilterLiked mocks base method
func (m *MockRepository) FilterLiked(params FilterParams) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterLiked", params)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterLiked indicates an expected call of FilterLiked
func (mr *MockRepositoryMockRecorder) FilterLiked(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLiked", reflect.TypeOf((*MockRepository)(nil).FilterLiked), params)
}

// FilterRegistered mocks base method
func (m *MockRepository) FilterRegistered(params FilterParams) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterRegistered", params)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterRegistered indicates an expected call of FilterRegistered
func (mr *MockRepositoryMockRecorder) FilterRegistered(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterRegistered", reflect.TypeOf((*MockRepository)(nil).FilterRegistered), params)
}

// FilterRecommended mocks base method
func (m *MockRepository) FilterRecommended(params FilterParams) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterRecommended", params)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterRecommended indicates an expected call of FilterRecommended
func (mr *MockRepositoryMockRecorder) FilterRecommended(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterRecommended", reflect.TypeOf((*MockRepository)(nil).FilterRecommended), params)
}

// FilterTagged mocks base method
func (m *MockRepository) FilterTagged(params FilterParams, tagId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterTagged", params, tagId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTagged indicates an expected call of FilterTagged
func (mr *MockRepositoryMockRecorder) FilterTagged(params, tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTagged", reflect.TypeOf((*MockRepository)(nil).FilterTagged), params, tagId)
}

// FilterSimilar mocks base method
func (m *MockRepository) FilterSimilar(params FilterParams, meetingId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterSimilar", params, meetingId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterSimilar indicates an expected call of FilterSimilar
func (mr *MockRepositoryMockRecorder) FilterSimilar(params, meetingId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterSimilar", reflect.TypeOf((*MockRepository)(nil).FilterSimilar), params, meetingId)
}

// SearchMeetings mocks base method
func (m *MockRepository) SearchMeetings(params FilterParams, meetingName string, limit int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchMeetings", params, meetingName, limit)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchMeetings indicates an expected call of SearchMeetings
func (mr *MockRepositoryMockRecorder) SearchMeetings(params, meetingName, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchMeetings", reflect.TypeOf((*MockRepository)(nil).SearchMeetings), params, meetingName, limit)
}
