// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package meeting is a generated GoMock package.
package meeting

import (
	gomock "github.com/golang/mock/gomock"
	models "konami_backend/internal/pkg/models"
	reflect "reflect"
)

// MockUseCase is a mock of UseCase interface
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CreateMeeting mocks base method
func (m *MockUseCase) CreateMeeting(authorId int, data models.MeetingData) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeeting", authorId, data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeeting indicates an expected call of CreateMeeting
func (mr *MockUseCaseMockRecorder) CreateMeeting(authorId, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeeting", reflect.TypeOf((*MockUseCase)(nil).CreateMeeting), authorId, data)
}

// GetMeeting mocks base method
func (m *MockUseCase) GetMeeting(meetingId, userId int, authorized bool) (models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeeting", meetingId, userId, authorized)
	ret0, _ := ret[0].(models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeeting indicates an expected call of GetMeeting
func (mr *MockUseCaseMockRecorder) GetMeeting(meetingId, userId, authorized interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeeting", reflect.TypeOf((*MockUseCase)(nil).GetMeeting), meetingId, userId, authorized)
}

// UpdateMeeting mocks base method
func (m *MockUseCase) UpdateMeeting(userId int, update models.MeetingUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeeting", userId, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMeeting indicates an expected call of UpdateMeeting
func (mr *MockUseCaseMockRecorder) UpdateMeeting(userId, update interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeeting", reflect.TypeOf((*MockUseCase)(nil).UpdateMeeting), userId, update)
}

// GetAll mocks base method
func (m *MockUseCase) GetAll(userId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", userId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockUseCaseMockRecorder) GetAll(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUseCase)(nil).GetAll), userId)
}

// FilterToday mocks base method
func (m *MockUseCase) FilterToday(userId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterToday", userId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterToday indicates an expected call of FilterToday
func (mr *MockUseCaseMockRecorder) FilterToday(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterToday", reflect.TypeOf((*MockUseCase)(nil).FilterToday), userId)
}

// FilterTomorrow mocks base method
func (m *MockUseCase) FilterTomorrow(userId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterTomorrow", userId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterTomorrow indicates an expected call of FilterTomorrow
func (mr *MockUseCaseMockRecorder) FilterTomorrow(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterTomorrow", reflect.TypeOf((*MockUseCase)(nil).FilterTomorrow), userId)
}

// FilterFuture mocks base method
func (m *MockUseCase) FilterFuture(userId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterFuture", userId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterFuture indicates an expected call of FilterFuture
func (mr *MockUseCaseMockRecorder) FilterFuture(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterFuture", reflect.TypeOf((*MockUseCase)(nil).FilterFuture), userId)
}

// FilterLiked mocks base method
func (m *MockUseCase) FilterLiked(userId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterLiked", userId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterLiked indicates an expected call of FilterLiked
func (mr *MockUseCaseMockRecorder) FilterLiked(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterLiked", reflect.TypeOf((*MockUseCase)(nil).FilterLiked), userId)
}

// FilterRegistered mocks base method
func (m *MockUseCase) FilterRegistered(userId int) ([]models.Meeting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterRegistered", userId)
	ret0, _ := ret[0].([]models.Meeting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterRegistered indicates an expected call of FilterRegistered
func (mr *MockUseCaseMockRecorder) FilterRegistered(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterRegistered", reflect.TypeOf((*MockUseCase)(nil).FilterRegistered), userId)
}
